[build]
  base      = "Exp-13"
  functions = "netlify/functions"
  publish   = "."
  command   = "pip install -r requirements.txt"

[functions]
  included_files = ["app.py"]

[[redirects]]
  from   = "/*"
  to     = "/.netlify/functions/api/:splat"
  status = 200
